# Generated by Django 4.2 on 2023-05-10 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('placa_carro', models.CharField(db_column='Placa_Carro', max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='Marca', max_length=50)),
                ('modelo', models.CharField(db_column='Modelo', max_length=50)),
                ('papeles', models.CharField(db_column='Papeles', max_length=100)),
            ],
            options={
                'db_table': 'carro',
            },
        ),
        migrations.CreateModel(
            name='Conductora',
            fields=[
                ('identificacion_cond', models.IntegerField(db_column='Identificacion_cond', primary_key=True, serialize=False)),
                ('nombre_cond', models.CharField(db_column='Nombre_cond', max_length=50)),
                ('correo', models.CharField(db_column='Correo', max_length=100)),
                ('contraseña', models.CharField(db_column='Contraseña', max_length=50)),
                ('celular', models.IntegerField(db_column='Celular')),
                ('placa_carro', models.OneToOneField(db_column='placa_carro', on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.carro')),
            ],
            options={
                'db_table': 'conductora',
            },
        ),
        migrations.CreateModel(
            name='Usuaria',
            fields=[
                ('identificacion_usu', models.IntegerField(db_column='Identificacion_usu', primary_key=True, serialize=False)),
                ('nombre_usu', models.CharField(db_column='Nombre_usu', max_length=50)),
                ('correo', models.CharField(db_column='Correo', max_length=100)),
                ('contraseña', models.CharField(db_column='Contraseña', max_length=50)),
                ('celular', models.IntegerField(db_column='Celular')),
            ],
            options={
                'db_table': 'usuaria',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.IntegerField(db_column='Id_viaje', primary_key=True, serialize=False)),
                ('origen', models.CharField(db_column='Origen', max_length=50)),
                ('destino', models.CharField(db_column='Destino', max_length=50)),
                ('precio', models.IntegerField(db_column='Precio')),
                ('distancia', models.IntegerField(db_column='Distancia')),
                ('tiempo', models.TimeField(db_column='Tiempo')),
                ('identificacion_cond', models.OneToOneField(db_column='Identificacion_cond', on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.conductora')),
                ('identificacion_usu', models.OneToOneField(db_column='Identificacion_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.usuaria')),
            ],
            options={
                'db_table': 'viaje',
            },
        ),
        migrations.CreateModel(
            name='Agendamientoviaje',
            fields=[
                ('id_agenda', models.IntegerField(db_column='Id_agenda', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.TimeField(db_column='Hora')),
                ('id_viaje', models.OneToOneField(db_column='Id_viaje', on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.viaje')),
                ('identificacion_usu', models.OneToOneField(db_column='Identificacion_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.usuaria')),
            ],
            options={
                'db_table': 'agendamientoviaje',
            },
        ),
    ]
