# Generated by Django 4.2 on 2023-05-23 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='identificacion_cond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='WebApp.conductora'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='identificacion_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='WebApp.usuaria'),
        ),
    ]
