# Generated by Django 4.2 on 2023-05-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_viaje_identificacion_cond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='tiempo',
            field=models.CharField(db_column='Tiempo', max_length=50),
        ),
    ]
